### ISSUE TITLE
Specify version of google-api-python-client in setup.py

### ISSUE THREAD

**Issue by asieira** [afilipovich/gglsbl#30]
Require at least that the version be >= 1.5.4 to ensure these CVEs have been fixed: https://nvd.nist.gov/vuln/search/results?adv_search=false&form_type=basic&results_type=overview&search_type=all&query=google+app+engine+python+sdk

**Comment by afilipovich** [comment]
Thanks @asieira, it's good to know about these vulnerabilities.
It seems however that they impact only when app runs not trusted code within App Engine SDK and do not affect `ggslbl`.

**Comment by asieira** [comment]
Good point, I hadn't analysed the CVEs that deeply. In any case, it might be a good idea to specify a minimum version going forward for as basic security hygiene, no? :)

**Comment by afilipovich** [comment]
Yes, that makes sense, however I do not want to be too aggressive with requiring latest version of dependencies for some users use system packages. Ubuntu 14LTS is still being maintained so I will use its packages versions as a reference.
https://www.ubuntu.com/info/release-end-of-life

**Comment by asieira** [comment]
My suggestion is that you do the following:
```
 install_requires=['google-api-python-client>=1.5.4,<2'],
```

This is pretty flexible, since [1.5.4](https://pypi.python.org/pypi/google-api-python-client/1.5.4) was released more than one year ago and is the first non-vulnerable version available.

**Comment by afilipovich** [comment]
Hi @asieira, I've been contemplating which version of dependencies to require and I think ones used in current Ubuntu LTS is most reasonable restriction. While it may permit libraries with unfixed vulnerabilities, `gglsbl` itself has very limited attack surface (its input are URLs) and significant vulnerabilities will be fixed by regular OS updates. Since `gglsbl` works with latest version of, say, `google-api-python-client`, it does not encourage installing outdated dependencies.
